### ISSUE TITLE
Encode files to Base64, transfer, and decode

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#1]
https://github.com/IPVS-AS/MBP/blob/8dff0bf527622ec36ab89ed930dd815b4f5b7083/src/main/java/org/citopt/connde/service/SSHDeployer.java#L173

**Comment by hirmerpl** [comment]
this could help: https://askubuntu.com/questions/178521/how-can-i-decode-a-base64-string-from-the-command-line

**Comment by schneijan** [comment]
Subtasks:
- [ ] Load the files not as plain text but as base64 encoded data url in the frontend
- [ ] Store the data url in the database instead of the plain text
- [ ] Transfer the base64 string to do dedicated network device
- [ ] Decode the base64 string on the device and create the corresponding file

**Comment by schneijan** [comment]
All files are now read, stored and delivered as base64 strings. Included a fallback for files that are still stored as plain text in the database.
