### ISSUE TITLE
SSHSession error on undeploying

### ISSUE THREAD

**Issue by amil-i** [IPVS-AS/MBP#135]
An IllegalArgumentException occurs when trying to undeploy two or more components (sensors, actuators or combinations) simultaneously.  The exception occurs only in some cases.

`IllegalArgumentException: non-zero exit code #1: sudo bash $HOME&#47;scripts&#47;connde5ca21c72ef84887fe49e7c68&#47;stop.sh`
`SSHSession.java:366`

**Comment by schneijan** [comment]
Did this occur with two components that use the same target device and the same adapter scripts (but not necessarily the same adapter entity)? Since identical adapter scripts create processes with the same name on the target device on deployment, there may be some side-effects when starting/stopping one of them. For example, the common stop adapter script uses `sudo kill -9 $(ps -ef | grep sensoradapter_temperature_stub.py | grep -v grep | awk '{print $2}')` to stop the execution which will actually stop all processes that use a script with name _sensoradapter_temperature_stub.py_ . The same holds for all other adapter scripts. In my opinion this is not a bug, just better adapter scripts need to be provided in practice.

**Comment by amil-i** [comment]
I was using the same adapter scripts for testing and I failed to see that this could yield any side effects, so I totally agree that this is not a bug of the system. Some guidelines on creating and using the adapter scripts would solve the problem.

**Comment by schneijan** [comment]
I created a new issue in terms of the documentation for adapters (#144) which also references the possible problems as described in here. Thus, I think this issue might be closed. If there are any objections from your side, please reopen. :-)
