### ISSUE TITLE
[BUG] Undesired behavior with Rules

### ISSUE THREAD

**Issue by mtfrigo** [IPVS-AS/MBP#216]
Hi,
 
I was trying to create an Rule to trigger an actuator action on our Openstack instance of MBP and it is throwing undesired behavior.
 
It looks like a bug related to the Rules, thrown when a Rule is triggered… I don’t know yet exactly why (unstable connections, actuator adapter code, rules code etc.)
 
I will write below all the steps I have done:
 
1. I created a sensor and deployed it.
2. I created an actuator and deployed it.
3. I created a rule action, a rule trigger and a rule definition
4.  I activated the rule definition
5. I was on the sensor page (which was suppose to trigger the rule)
6. I triggered the rule with the desired sensor behavior
7. It was not possible to go to the Rule Definitions page anymore (HTML 500 error)
 
The link below contain the HTML file of the error.
[HTTP Status 500 – Internal Server Error](https://drive.google.com/file/d/1-u_n3JVQZTmgvMwE8_7G8weYnMY5oXSd/view?usp=sharing)

**Comment by mtfrigo** [comment]
I found that my actuator script was causing this. Although I couldn't figure out why ...

But it happened when I used a Rule Action binded to the Actuator that uses this script ... Just at the moment when the Rule Definition was triggered, which uses the Rule Action mentioned above, the error occurred and I was not able to access the Rule Definition page...

Sometimes an similar error occured, but I was able to fix it by deleting the trigger which the Rule Definition was binded to...

**Comment by schneijan** [comment]
Hey,

sorry for the long delay. I spotted the cause of this annoying issue now, I hope. Looks like it was caused when a rule action was deleted that is part of an enabled rule. As soon as the trigger of this rule was triggered (due to matching incoming sensor values), the RuleEngine component tried to access the no longer existing rule which subsequently led to the failure. Now the rules should be automatically disabled before deletion (after the deletion of its rule action was issued) which removes all references from the RuleEngine. Thank you again for the detailed descriptions, this was very helpful!

Could you please have a look at the pull request #221 and verify whether the problem has been resolved?

**Comment by mtfrigo** [comment]
Hello,

What a great news! :D

Tomorrow I will test it and give you a feedback :)
