### ISSUE TITLE
Create device in Environment Model 

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#335]
It is not possible to register a device in the Environment Model. It shows a message error:

<img width="508" alt="Screenshot 2020-07-14 at 15 50 45" src="https://user-images.githubusercontent.com/44437898/87433605-cb795600-c5e9-11ea-9c00-0512a3282978.png">

It can occur due to different fields to register a new device in the Environment Model and in the device:

<img width="1272" alt="Screenshot 2020-07-14 at 15 46 57" src="https://user-images.githubusercontent.com/44437898/87433505-ab499700-c5e9-11ea-9aea-c458d05b2eae.png">

<img width="1279" alt="Screenshot 2020-07-14 at 15 47 31" src="https://user-images.githubusercontent.com/44437898/87433514-ac7ac400-c5e9-11ea-96e3-56c0245fbc24.png">

**Comment by schneijan** [comment]
In my opinion this is no bug; it happens because mandatory fields like IP address and name are missing. I think it should be sufficient to make the error messages a little bit more descriptive.

**Comment by tatianegava** [comment]
Hi Jan, it was not missing. I inserted them, but did not work. 
I did the same in device, and worked.

**Comment by ana-silva** [comment]
Hey guys, unfortunately it is a bug. Like @tatianegava said, with all atributes filled, with exception of the key because we were using the password instead, an error still occurred. One thing I didn't test is if the error also occurs when I provide the key instead of the password.

@schneijan a more descriptive error message would be definitely nice :)
