### ISSUE TITLE
Java script errors occur in each view

### ISSUE THREAD

**Issue by ana-silva** [IPVS-AS/MBP#47]
Error message:

Error: data._embedded.valueLogs[0] is undefined
load/</</<@http://192.168.209.164:8080/MBP/js/controllers/sensors/SensorDetailsController.js:226:82
f/<@http://192.168.209.164:8080/MBP/js/angular.js:9:13470
$eval@http://192.168.209.164:8080/MBP/js/angular.js:10:5205
$digest@http://192.168.209.164:8080/MBP/js/angular.js:10:3767
$apply@http://192.168.209.164:8080/MBP/js/angular.js:10:5485
l@http://192.168.209.164:8080/MBP/js/angular.js:8:1946
O@http://192.168.209.164:8080/MBP/js/angular.js:9:51
wf/</w.onload@http://192.168.209.164:8080/MBP/js/angular.js:9:590
 angular.js:9:8667
	e/< http://192.168.209.164:8080/MBP/js/angular.js:9:8667
	He/this.$get</< http://192.168.209.164:8080/MBP/js/angular.js:7:13641
	f/< http://192.168.209.164:8080/MBP/js/angular.js:9:13553
	$eval http://192.168.209.164:8080/MBP/js/angular.js:10:5205
	$digest http://192.168.209.164:8080/MBP/js/angular.js:10:3767
	$apply http://192.168.209.164:8080/MBP/js/angular.js:10:5485
	l http://192.168.209.164:8080/MBP/js/angular.js:8:1946
	O http://192.168.209.164:8080/MBP/js/angular.js:9:51
	wf/</w.onload http://192.168.209.164:8080/MBP/js/angular.js:9:590

**Comment by schneijan** [comment]
Steps to reproduce:

1. Choose one sensor from the sensors list
2. Go back to the sensor overview
3. Now the javascript error occurs multiple times in the console

In the frontend, an interval timer is set in order to retrieve sensor data on a regular basis. However, this timer is not unset after the page is switched and thus causes the error messages. Some further investigation is needed in order to come up with an appropriate solution.
