### ISSUE TITLE
When deleting Components, associated ones are not deleted.

### ISSUE THREAD

**Issue by katja-seb** [IPVS-AS/MBP#503]
When deleting some components, components that contain them should also be deleted. 
The message which components will be deleted additionally is displayed, but the HandleBeforeDelete methods of the EventHandlers are never called. 

Thus for example sensors exist, which don't have an operator any more.

**Comment by schneijan** [comment]
This is already fixed in first_release branch. Due to the major restructurings that were necessary for the policies, event handler do not work anymore and can be deleted. Furthermore we decided to prevent the user from deleting a entity that is still in use by another entity instead of implementing large deletion cascade chains.
