### ISSUE TITLE
Button disappears when starting an operator in a sensor with required parameter missing

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#527]
I have tried to start an operator with no value in the required parameter filed, it showed me an error about the missed parameter. However,  when I tried to include a number in the parameter field, I realised that the Start button disappeared. 

If the user wait for the reload from the device, the button reappears. However, it takes a long time for a user.

missing button:
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_18636.png)

error message:
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_18638.png)

#### Precondition
MacOSBigSur
Chrome - Version 88.0.4324.150 (Official Build) (x86_64)

It was used the: Temperature Stub Param Operator -https://github.com/IPVS-AS/MBP/tree/master/resources/operators/extraction/temperature_stub_param

#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| In the main Navigation Menu, select IoT Hardware -&gt; Sensors| Sensor page is opened| Pass |
| 2| Click on Sensor Temperature Stub Param| Sensor details page is opened| Pass |
| 3| Click on Install  Operator and start operator without any value in interval| Error message is displayed| Pass |
| 4| Insert interval parameter: 5| Parameter is ncluded| Fail |
| 5| Click Deploy Operator and start operator| Data is displayed with interval from 5 seconds| Fail |

**Comment by tatianegava** [comment]
https://mbp.testquality.com defect [D4](https://mbp.testquality.com/project/11022/result/2249297/defect/7500). Do not remove or edit.

**Comment by ana-silva** [comment]
We should check if a parameter value is entered on the client side, if not the "Start" button should be disabled. In general, the buttons should not disappear.

**Comment by schneijan** [comment]
The buttons disappear, because we do not know in which state the device currently is (indicated by the grey bar and description). Without knowing the device's state, we don't know whether we should display the "deploy" button, the "start", the "stop" button or the "undeploy" button. Thus, the buttons are hidden.

It's always possible to trigger the refresh of the device's state automatically by clicking the small refresh icon in the top right corner.
![image](https://user-images.githubusercontent.com/44969037/108141220-96733b80-70c3-11eb-8a80-5e124221faeb.png)

I think the best solution would be to just check the parameter fields on client side and avoid to set the device's state to unknown. Then nothing should disappear.

**Comment by ana-silva** [comment]
Hi @schneijan, is it realistic to work on this change for the first release? If not, we can update the documentation with the hint to "Refresh in case the state is unknown" and work on this later

**Comment by schneijan** [comment]
Solved by adding a status code check
